OCCPath = ViewWindow/opencascade/build
OCCIncludePath = $$OCCPath/include/opencascade
OCCLibPath = $$OCCPath/lin64/gcc/lib
INCLUDEPATH += $$OCCIncludePath
unix{
OCCPath = $$PWD/opencascade/build
occinclude = $$OCCPath/include/opencascade
occlib = $$OCCPath/lin64/gcc/lib
}
INCLUDEPATH += $$occinclude
CONFIG += C++11
JsonPath = /usr/local/lib
LIBS += -L$$JsonPath -ljsoncpp
LIBS += -L$$occlib -lTKBinL
LIBS += -L$$occlib -lTKCDF
LIBS += -L$$occlib -lTKG3d
LIBS += -L$$occlib -lTKMeshVS
LIBS += -L$$occlib -lTKShHealing
LIBS += -L$$occlib -lTKTObjDRAW
LIBS += -L$$occlib -lTKXCAF
LIBS += -L$$occlib -lTKXml
LIBS += -L$$occlib -lTKDCAF
LIBS += -L$$occlib -lTKGeomAlgo
LIBS += -L$$occlib -lTKOffset
LIBS += -L$$occlib -lTKStdL
LIBS += -L$$occlib -lTKTObj
LIBS += -L$$occlib -lTKXmlTObj
LIBS += -L$$occlib -lTKBinTObj
LIBS += -L$$occlib -lTKDraw
LIBS += -L$$occlib -lTKGeomBase
LIBS += -L$$occlib -lTKOpenGl
LIBS += -L$$occlib -lTKStd
LIBS += -L$$occlib -lTKTopAlgo
LIBS += -L$$occlib -lTKXDEDRAW
LIBS += -L$$occlib -lTKXmlXCAF
LIBS += -L$$occlib -lTKBinXCAF
LIBS += -L$$occlib -lTKernel
LIBS += -L$$occlib -lTKHLR
LIBS += -L$$occlib -lTKOpenGlTest
LIBS += -L$$occlib -lTKSTEP209
LIBS += -L$$occlib -lTKTopTest
LIBS += -L$$occlib -lTKXDEIGES
LIBS += -L$$occlib -lTKXSBase
LIBS += -L$$occlib -lTKBool
LIBS += -L$$occlib -lTKIGES
LIBS += -L$$occlib -lTKPrim
LIBS += -L$$occlib -lTKSTEPAttr
LIBS += -L$$occlib -lTKV3d
LIBS += -L$$occlib -lTKXSDRAW
LIBS += -L$$occlib -lTKBO
LIBS += -L$$occlib -lTKFeat
LIBS += -L$$occlib -lTKLCAF
LIBS += -L$$occlib -lTKQADraw
LIBS += -L$$occlib -lTKSTEPBase
LIBS += -L$$occlib -lTKVCAF
LIBS += -L$$occlib -lTKBRep
LIBS += -L$$occlib -lTKFillet
LIBS += -L$$occlib -lTKMath
LIBS += -L$$occlib -lTKRWMesh
LIBS += -L$$occlib -lTKSTEP
LIBS += -L$$occlib -lTKViewerTest
LIBS += -L$$occlib -lTKXMesh
LIBS += -L$$occlib -lTKCAF
LIBS += -L$$occlib -lTKG2d
LIBS += -L$$occlib -lTKMesh
LIBS += -L$$occlib -lTKService
LIBS += -L$$occlib -lTKSTL
LIBS += -L$$occlib -lTKVRML
LIBS += -L$$occlib -lTKXmlL
FORMS +=
HEADERS +=
SOURCES +=