PROJECT(CAMAlgorithm)
CMAKE_MINIMUM_REQUIRED(VERSION 3.12)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_EXTENSIONS OFF)
find_package(TBB REQUIRED VERSION 2021.11.0)
option(EnableView "Enable debug mode" OFF)
if(EnableView)
    message(STATUS "Offset2D 编译可视化工具")
    add_subdirectory(./OperateView)
endif()
#add_subdirectory(./OperateView)
add_subdirectory(./OperGeom3D)

aux_source_directory(./ToolTrajectoryAlg/ SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/DynamicProgram SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/DynamicProgram/EqudistArea SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/DynamicProgram/GeneratePath SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/DynamicProgram/EquBndIslLoop SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/DynamicProgram/GenerateTrajectory SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/EquidCurve/PreprocLoop SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/EquidCurve/EquidCurve SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/EquidCurve/EquidCurve/EquidCurve SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/EquidCurve/RegulateOftVal SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/EquidCurve/RegulateOftVal/BaseElemCorner SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/EquidCurve/RegulateOftVal/BaseEquidInt SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/EquidCurve/RegulateOftVal/BasePassage SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/EquidCurve/RegulateOftVal/GeomAreaCase SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/EquidCurve/LoopSelInt SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryCalculate/GeomFitting2D SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryCalculate/GeomFitting2D/Fitt2D SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryCalculate/GeomCalculate SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryCalculate/GeomIntersect SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryCalculate/GeomQuality SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryCalculate/RelativeContain SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryCalculate/OperateCurve SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/OperCurve2D/OperCurve2D SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/OperCurve2D/NumeCalculate SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/OperCurve2D/OperateOftString SRC_DIR)
# aux_source_directory(./ToolTrajectoryAlg/PlaneStyleMilling SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/ResultTreatment/CreateHelix SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/ResultTreatment/MachineDirection SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/ResultTreatment/SmoothStrategy SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/ResultTreatment/SmoothStrategy/SmoothStrategy SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/ResultTreatment/AlongPathEntry SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/ResultTreatment/SpecifyCutEntry SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/ResultTreatment/ConnectAreaLoop SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/ResultTreatment/OffsetPrecision SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/ResultTreatment/OperatePath SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryClip/ClipIntersect SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryClip/GeomBoolUnion SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryClip/GeomBoolSubtract SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryClip/RegionLoopInt SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryClip/GeomBoolInt SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryClip/BoolClipAux SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryClip SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryClip/RegionBool/AuxCalculate SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryClip/RegionBool/RegionSubtract SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/GeometryClip/RegionBool SRC_DIR)
aux_source_directory(./ToolTrajectoryAlg/OperateDebug SRC_DIR)
# aux_source_directory(./ClipOffsetAPI SRC_DIR)
# aux_source_directory(./OperateView/OperateView SRC_DIR)

add_library(CAMAlgorithm ${SRC_DIR})
target_include_directories(CAMAlgorithm PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>)
target_include_directories(CAMAlgorithm PUBLIC $<INSTALL_INTERFACE:include>)
target_link_libraries(CAMAlgorithm PRIVATE TBB::tbb)
install(DIRECTORY . DESTINATION include/CAMAlgorithm FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp" PATTERN "*.hxx" PATTERN "build" EXCLUDE)
install(TARGETS CAMAlgorithm EXPORT ${PROJECT_NAME}Targets RUNTIME DESTINATION lib LIBRARY DESTINATION lib ARCHIVE DESTINATION lib)
install(EXPORT CAMAlgorithmTargets FILE ${PROJECT_NAME}Targets.cmake DESTINATION lib/cmake/CAMAlgorithm)
include(CMakePackageConfigHelpers)
configure_package_config_file("CAMAlgorithm.cmake.in" "${CMAKE_CURRENT_BINARY_DIR}/CAMAlgorithmConfig.cmake" INSTALL_DESTINATION lib/cmake/CAMAlgorithm)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/CAMAlgorithmConfig.cmake DESTINATION lib/cmake/CAMAlgorithm)
if (MSVC)
    add_compile_options(/MP)
    add_compile_options(/wd4267)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4267")
    target_compile_options(CAMAlgorithm PUBLIC /utf-8)
else (UNIX)
        target_compile_options(CAMAlgorithm PUBLIC -fPIC)
endif()



