PROJECT(OperateView)
CMAKE_MINIMUM_REQUIRED(VERSION 3.12)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 17)
find_package(QT NAMES Qt6 Qt5 COMPONENTS Widgets REQUIRED)
find_package(Qt${QT_VERSION_MAJOR} COMPONENTS Widgets REQUIRED)
aux_source_directory(./ SRC_DIR)
aux_source_directory(./ViewGeom SRC_DIR)
aux_source_directory(./ViewWind SRC_DIR)
set(forms ./ViewWind/mainwindow.ui)
set(user_source ./ViewWind/occQt.qrc)
add_executable(OperateView ${src} ${forms} ${user_source})
target_link_libraries(OperateView PRIVATE cnc-cam-core Qt${QT_VERSION_MAJOR}::Widgets)
set(CMAKE_MAKE_PROGRAM "make -j16")
if(QT_VERSION_MAJOR EQUAL 6)
    qt_finalize_executable(OperateView)
endif()
if(MSVC)
    add_compile_options(/MP)
    add_compile_options(/wd4267)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4267")
    target_compile_options(OperateView PUBLIC /utf-8 /MP)
else (UNIX)
        target_compile_options(OperateView PUBLIC -fPIC)
endif(MSVC)