PROJECT(OperGeom3D)
CMAKE_MINIMUM_REQUIRED(VERSION 3.12)
set(CMAKE_PREFIX_PATH ../ToolTrajectoryAlg/ThirdPart/TBB/TBB_2021_11)
find_package(TBB REQUIRED VERSION 2021.11.0)
aux_source_directory(./ SRC_DIR)
aux_source_directory(./GeomCalc3D SRC_DIR)
aux_source_directory(./OperCurve3D SRC_DIR)
add_library(OperGeom3D ${SRC_DIR})
target_include_directories(OperGeom3D PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>)
target_include_directories(OperGeom3D PUBLIC $<INSTALL_INTERFACE:include>)
target_link_libraries(OperGeom3D PRIVATE TBB::tbb)
if (MSVC)
    add_compile_options(/MP)
    add_compile_options(/wd4267)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4267")
    target_compile_options(OperGeom3D PUBLIC /utf-8)
else (UNIX)
        target_compile_options(OperGeom3D PUBLIC -fPIC)
endif()